import type { Event, Application, AdminUser, FAQ, DashboardStats } from '../types';

export const MOCK_EVENTS: Event[] = [
  {
    id: 1,
    title: "O'zbekiston san'ati: Zamonaviy yo'nalishlar xalqaro konferensiyasi",
    type: "conference",
    status: "ongoing",
    shortDescription: "Zamonaviy san'at va madaniyat sohasidagi global tendensiyalarni muhokama qilish uchun xalqaro mutaxassislar yig'ini.",
    fullDescription: "Ushbu xalqaro konferensiya O'zbekiston san'ati va madaniyatining zamonaviy rivojlanish yo'nalishlarini o'rganish, xorijiy hamkorlar bilan tajriba almashish va ilmiy hamkorlikni kuchaytirish maqsadida tashkil etilgan. Tadbirda 25 dan ortiq mamlakatlardan 300+ mutaxassis ishtirok etadi.",
    startDate: "2026-09-15",
    endDate: "2026-09-17",
    registrationDeadline: "2026-08-31",
    venue: "Toshkent, O'zbekiston Milliy san'at muzeyi",
    bannerUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&h=500&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1587825140708-dfaf72ae4b04?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1569974498991-d3c12a504f95?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800&h=600&fit=crop&auto=format",
    ],
    registrationEnabled: true,
    applicationsCount: 147,
    createdAt: "2026-01-10",
    translations: {
      uz: {
        title: "O'zbekiston san'ati: Zamonaviy yo'nalishlar xalqaro konferensiyasi",
        shortDescription: "Zamonaviy san'at va madaniyat sohasidagi global tendensiyalarni muhokama qilish uchun xalqaro mutaxassislar yig'ini.",
        fullDescription: "Ushbu xalqaro konferensiya O'zbekiston san'ati va madaniyatining zamonaviy rivojlanish yo'nalishlarini o'rganish, xorijiy hamkorlar bilan tajriba almashish va ilmiy hamkorlikni kuchaytirish maqsadida tashkil etilgan. Tadbirda 25 dan ortiq mamlakatlardan 300+ mutaxassis ishtirok etadi.",
        venue: "Toshkent, O'zbekiston Milliy san'at muzeyi",
      },
      ru: {
        title: "Искусство Узбекистана: Международная конференция по современным направлениям",
        shortDescription: "Встреча международных экспертов для обсуждения глобальных тенденций в области современного искусства и культуры.",
        fullDescription: "Эта международная конференция организована с целью изучения современных направлений развития искусства и культуры Узбекистана, обмена опытом с зарубежными партнерами и укрепления научного сотрудничества. В мероприятии примут участие более 300 экспертов из 25 стран.",
        venue: "Ташкент, Государственный музей искусств Узбекистана",
      },
      en: {
        title: "Uzbekistan Art: International Conference on Modern Trends",
        shortDescription: "A gathering of international experts to discuss global trends in contemporary art and culture.",
        fullDescription: "This international conference is organized to explore modern development trends in Uzbekistan's art and culture, exchange experience with foreign partners, and strengthen scientific cooperation. Over 300 experts from more than 25 countries will participate.",
        venue: "Tashkent, State Museum of Arts of Uzbekistan",
      },
    },
  },
  {
    id: 2,
    title: "Markaziy Osiyo san'at festivali va ko'rgazmasi 2026",
    type: "exhibition",
    status: "planned",
    shortDescription: "Markaziy Osiyo mamlakatlari san'atkorlarining asarlari namoyish etiladigan yirik ko'rgazma.",
    fullDescription: "Markaziy Osiyo san'at festivali mintaqaning boy madaniy merosini va zamonaviy ijodiy salohiyatini namoyish etuvchi muhim tadbirdir. Ko'rgazmada rangtasvir, haykaltaroshlik, grafika va raqamli san'at asarlari taqdim etiladi.",
    startDate: "2026-10-20",
    endDate: "2026-10-28",
    registrationDeadline: "2026-09-30",
    venue: "Toshkent, Yangi O'zbekiston ko'rgazmalar markazi",
    bannerUrl: "https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?w=1200&h=500&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1577083552431-6e5fd01988ec?w=800&h=600&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1536924940846-227afb31e2a5?w=800&h=600&fit=crop&auto=format",
    ],
    registrationEnabled: true,
    applicationsCount: 89,
    createdAt: "2026-02-15",
    translations: {
      uz: {
        title: "Markaziy Osiyo san'at festivali va ko'rgazmasi 2026",
        shortDescription: "Markaziy Osiyo mamlakatlari san'atkorlarining asarlari namoyish etiladigan yirik ko'rgazma.",
        fullDescription: "Markaziy Osiyo san'at festivali mintaqaning boy madaniy merosini va zamonaviy ijodiy salohiyatini namoyish etuvchi muhim tadbirdir. Ko'rgazmada rangtasvir, haykaltaroshlik, grafika va raqamli san'at asarlari taqdim etiladi.",
        venue: "Toshkent, Yangi O'zbekiston ko'rgazmalar markazi",
      },
      ru: {
        title: "Фестиваль и выставка искусства Центральной Азии 2026",
        shortDescription: "Крупная выставка произведений художников стран Центральной Азии.",
        fullDescription: "Фестиваль искусства Центральной Азии является важным мероприятием, демонстрирующим богатое культурное наследие и современный творческий потенциал региона. На выставке представлены живопись, скульптура, графика и цифровое искусство.",
        venue: "Ташкент, Выставочный центр Новый Узбекистан",
      },
      en: {
        title: "Central Asian Art Festival and Exhibition 2026",
        shortDescription: "A major exhibition featuring works by artists from Central Asian countries.",
        fullDescription: "The Central Asian Art Festival is a significant event showcasing the rich cultural heritage and modern creative potential of the region. The exhibition presents paintings, sculptures, graphics, and digital art.",
        venue: "Tashkent, New Uzbekistan Exhibition Center",
      },
    },
  },
  {
    id: 3,
    title: "Madaniyat va meros simpoziumlari: Ipak yo'li an'analari",
    type: "symposium",
    status: "planned",
    shortDescription: "Ipak yo'li madaniy merosi va zamonaviy ta'siri bo'yicha ilmiy muhokamalar.",
    fullDescription: "Simpozium Ipak yo'li mamlakatlarining madaniy merosi, an'analari va zamonaviy san'atga ta'sirini o'rganishga bag'ishlangan. Ilmiy ma'ruzalar, panel muhokamalar va amaliy ustaxonalar rejalashtirilgan.",
    startDate: "2026-11-05",
    endDate: "2026-11-07",
    registrationDeadline: "2026-10-15",
    venue: "Samarqand, Registon majmuasi yaqinidagi Konferensiya markazi",
    bannerUrl: "https://images.unsplash.com/photo-1589561253898-768105ca91a8?w=1200&h=500&fit=crop&auto=format",
    gallery: [],
    registrationEnabled: true,
    applicationsCount: 43,
    createdAt: "2026-03-01",
    translations: {
      uz: {
        title: "Madaniyat va meros simpoziumlari: Ipak yo'li an'analari",
        shortDescription: "Ipak yo'li madaniy merosi va zamonaviy ta'siri bo'yicha ilmiy muhokamalar.",
        fullDescription: "Simpozium Ipak yo'li mamlakatlarining madaniy merosi, an'analari va zamonaviy san'atga ta'sirini o'rganishga bag'ishlangan. Ilmiy ma'ruzalar, panel muhokamalar va amaliy ustaxonalar rejalashtirilgan.",
        venue: "Samarqand, Registon majmuasi yaqinidagi Konferensiya markazi",
      },
      ru: {
        title: "Симпозиумы культуры и наследия: Традиции Шелкового пути",
        shortDescription: "Научные дискуссии о культурном наследии Шелкового пути и его современном влиянии.",
        fullDescription: "Симпозиум посвящен изучению культурного наследия, традиций и влияния стран Шелкового пути на современное искусство. Запланированы научные доклады, панельные дискуссии и практические мастер-классы.",
        venue: "Самарканд, Конференц-центр возле ансамбля Регистан",
      },
      en: {
        title: "Culture and Heritage Symposiums: Silk Road Traditions",
        shortDescription: "Scientific discussions on the Silk Road cultural heritage and its modern influence.",
        fullDescription: "The symposium is dedicated to studying the cultural heritage, traditions, and influence of Silk Road countries on contemporary art. Scientific lectures, panel discussions, and practical workshops are scheduled.",
        venue: "Samarkand, Conference Center near Registan Complex",
      },
    },
  },
  {
    id: 4,
    title: "Xalqaro musiqa va sahnalashtirish san'ati forumi",
    type: "forum",
    status: "completed",
    shortDescription: "Musiqa va teatr sohasidagi global tendensiyalarni muhokama qilish platformasi.",
    fullDescription: "Ushbu forum musiqa va teatr san'atining rivojlanish yo'nalishlarini, zamonaviy sahna texnologiyalarini va xalqaro hamkorlik imkoniyatlarini muhokama qilish uchun mo'ljallangan.",
    startDate: "2026-05-10",
    endDate: "2026-05-12",
    registrationDeadline: "2026-04-20",
    venue: "Toshkent, Alisher Navoiy nomidagi Davlat opera va balet teatri",
    bannerUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200&h=500&fit=crop&auto=format",
    gallery: [
      "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=800&h=600&fit=crop&auto=format",
    ],
    registrationEnabled: false,
    applicationsCount: 215,
    createdAt: "2025-12-01",
    translations: {
      uz: {
        title: "Xalqaro musiqa va sahnalashtirish san'ati forumi",
        shortDescription: "Musiqa va teatr sohasidagi global tendensiyalarni muhokama qilish platformasi.",
        fullDescription: "Ushbu forum musiqa va teatr san'atining rivojlanish yo'nalishlarini, zamonaviy sahna texnologiyalarini va xalqaro hamkorlik imkoniyatlarini muhokama qilish uchun mo'ljallangan.",
        venue: "Toshkent, Alisher Navoiy nomidagi Davlat opera va balet teatri",
      },
      ru: {
        title: "Международный форум музыкального и сценического искусства",
        shortDescription: "Платформа для обсуждения глобальных тенденций в области музыки и театра.",
        fullDescription: "Этот форум предназначен для обсуждения направлений развития музыкального и театрального искусства, современных сценических технологий и возможностей международного сотрудничества.",
        venue: "Ташкент, Государственный академический большой театр имени Алишера Навои",
      },
      en: {
        title: "International Music and Performing Arts Forum",
        shortDescription: "A platform to discuss global trends in music and theatre.",
        fullDescription: "This forum is designed to discuss development trends in music and performing arts, modern stage technologies, and international cooperation opportunities.",
        venue: "Tashkent, Alisher Navoiy State Academic Opera and Ballet Theatre",
      },
    },
  },
  {
    id: 5,
    title: "Raqamli san'at va texnologiyalar bo'yicha xalqaro seminar",
    type: "workshop",
    status: "planned",
    shortDescription: "Raqamli texnologiyalarni san'atda qo'llash bo'yicha amaliy seminar.",
    fullDescription: "Zamonaviy raqamli vositalar, sun'iy intellekt va san'at o'rtasidagi munosabatlarni o'rganuvchi intensiv seminar. Ishtirokchilar amaliy ko'nikmalar va bilimlarni oshirish imkoniyatiga ega bo'ladilar.",
    startDate: "2026-12-01",
    endDate: "2026-12-03",
    registrationDeadline: "2026-11-15",
    venue: "Toshkent, O'zbekiston Davlat san'at va madaniyat instituti",
    bannerUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=1200&h=500&fit=crop&auto=format",
    gallery: [],
    registrationEnabled: true,
    applicationsCount: 28,
    createdAt: "2026-04-01",
    translations: {
      uz: {
        title: "Raqamli san'at va texnologiyalar bo'yicha xalqaro seminar",
        shortDescription: "Raqamli texnologiyalarni san'atda qo'llash bo'yicha amaliy seminar.",
        fullDescription: "Zamonaviy raqamli vositalar, sun'iy intellekt va san'at o'rtasidagi munosabatlarni o'rganuvchi intensiv seminar. Ishtirokchilar amaliy ko'nikmalar va bilimlarni oshirish imkoniyatiga ega bo'ladilar.",
        venue: "Toshkent, O'zbekiston Davlat san'at va madaniyat instituti",
      },
      ru: {
        title: "Международный семинар по цифровому искусству и технологиям",
        shortDescription: "Практический семинар по применению цифровых технологий в искусстве.",
        fullDescription: "Интенсивный семинар, изучающий связь между современными цифровыми инструментами, искусственным интеллектом и искусством. Участники смогут повысить практические навыки и знания.",
        venue: "Ташкент, Государственный институт искусств и культуры Узбекистана",
      },
      en: {
        title: "International Workshop on Digital Art and Technology",
        shortDescription: "Practical workshop on applying digital technologies in art.",
        fullDescription: "An intensive workshop exploring the relationship between modern digital tools, artificial intelligence, and art. Participants will have the opportunity to enhance practical skills and knowledge.",
        venue: "Tashkent, State Institute of Arts and Culture of Uzbekistan",
      },
    },
  },
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 1,
    applicationId: "CF-2026-000001",
    fullName: "Azimov Jasur Baxtiyor o'g'li",
    dateOfBirth: "1985-03-15",
    gender: "male",
    phone: "+998901234567",
    email: "azimov.jasur@mail.uz",
    organization: "O'zbekiston Milliy universiteti",
    position: "San'atshunoslik bo'limi professori",
    country: "O'zbekiston",
    regionId: 1,
    regionName: "Toshkent shahri",
    districtId: 1,
    districtName: "Yunusobod",
    eventId: 1,
    eventTitle: "O'zbekiston san'ati: Zamonaviy yo'nalishlar xalqaro konferensiyasi",
    presentationTitle: "Zamonaviy o'zbek tasviriy san'atida milliy o'ziga xoslik",
    abstract: "Ushbu tadqiqot so'nggi o'n yillikda o'zbek tasviriy san'atidagi milliy elementlarning zamonaviy ifodasi va global tendensiyalar bilan uyg'unlashuvini o'rganadi.",
    documentUrl: "/files/abstract_001.pdf",
    photoUrl: "/files/photo_001.jpg",
    status: "approved",
    adminComment: "Ajoyib taqdimot. Tasdiqlandi.",
    submittedAt: "2026-07-15T10:30:00",
    updatedAt: "2026-07-20T14:00:00",
    translations: {
      uz: { adminComment: "Ajoyib taqdimot. Tasdiqlandi." },
      ru: { adminComment: "Отличная презентация. Одобрено." },
      en: { adminComment: "Excellent presentation. Approved." },
    },
  },
  {
    id: 2,
    applicationId: "CF-2026-000002",
    fullName: "Nazarova Nilufar Hamidovna",
    dateOfBirth: "1990-07-22",
    gender: "female",
    phone: "+998932345678",
    email: "nazarova.nilufar@samarkand.uz",
    organization: "Samarqand Davlat universiteti",
    position: "Madaniyatshunoslik kafedrasi dotsenti",
    country: "O'zbekiston",
    regionId: 3,
    regionName: "Samarqand viloyati",
    districtId: 1,
    districtName: "Samarqand",
    eventId: 1,
    eventTitle: "O'zbekiston san'ati: Zamonaviy yo'nalishlar xalqaro konferensiyasi",
    presentationTitle: "Ipak yo'li madaniy ta'sirining zamonaviy o'zbek san'atidagi aksi",
    abstract: "Tadqiqot Ipak yo'li orqali kirib kelgan madaniy ta'sirlarning hozirgi zamon o'zbek san'atida qanday ifodalanishini tahlil qiladi.",
    documentUrl: "/files/abstract_002.pdf",
    status: "under_review",
    submittedAt: "2026-07-16T09:15:00",
    updatedAt: "2026-07-18T11:00:00",
  },
  {
    id: 3,
    applicationId: "CF-2026-000003",
    fullName: "Qodirov Bobur Alisher o'g'li",
    dateOfBirth: "1978-11-08",
    gender: "male",
    phone: "+998712345678",
    email: "qodirov.b@art.uz",
    organization: "O'zbekiston Davlat san'at va madaniyat instituti",
    position: "Tasviriy san'at kafedrasi mudiri",
    country: "O'zbekiston",
    regionId: 1,
    regionName: "Toshkent shahri",
    districtId: 3,
    districtName: "Yakkasaroy",
    eventId: 2,
    eventTitle: "Markaziy Osiyo san'at festivali va ko'rgazmasi 2026",
    presentationTitle: "Zamonaviy rangtasvirda an'anaviy naqsh va geometriya",
    abstract: "Ushbu ish o'zbek an'anaviy naqsh va geometrik shakllarning zamonaviy rangtasvirga integratsiyasini ko'rib chiqadi.",
    status: "submitted",
    submittedAt: "2026-07-20T14:22:00",
    updatedAt: "2026-07-20T14:22:00",
  },
  {
    id: 4,
    applicationId: "CF-2026-000004",
    fullName: "Yusupova Malika Shuhrat qizi",
    dateOfBirth: "1995-05-30",
    gender: "female",
    phone: "+998935566778",
    email: "malika.yusupova@gmail.com",
    organization: "Toshkent Davlat texnika universiteti",
    position: "Dizayn kafedrasi o'qituvchisi",
    country: "O'zbekiston",
    regionId: 1,
    regionName: "Toshkent shahri",
    districtId: 2,
    districtName: "Chilonzor",
    eventId: 1,
    eventTitle: "O'zbekiston san'ati: Zamonaviy yo'nalishlar xalqaro konferensiyasi",
    presentationTitle: "Raqamli dizayn va milliy identichlik",
    abstract: "Raqamli texnologiyalar va milliy dizayn elementlarining uyg'unlashuvi bo'yicha tadqiqot.",
    status: "info_required",
    adminComment: "Iltimos, tadqiqotingizning metodologiyasi haqida qo'shimcha ma'lumot bering.",
    submittedAt: "2026-07-22T16:45:00",
    updatedAt: "2026-07-25T10:30:00",
    translations: {
      uz: { adminComment: "Iltimos, tadqiqotingizning metodologiyasi haqida qo'shimcha ma'lumot bering." },
      ru: { adminComment: "Пожалуйста, предоставьте дополнительную информацию о методологии вашего исследования." },
      en: { adminComment: "Please provide additional information regarding the methodology of your research." },
    },
  },
  {
    id: 5,
    applicationId: "CF-2026-000005",
    fullName: "Toshmatov Sanjar Ravshan o'g'li",
    dateOfBirth: "1988-09-12",
    gender: "male",
    phone: "+998907788990",
    email: "toshmatov.sanjar@buxoro.uz",
    organization: "Buxoro Davlat universiteti",
    position: "Tarix va san'at tarixi professori",
    country: "O'zbekiston",
    regionId: 4,
    regionName: "Buxoro viloyati",
    districtId: 1,
    districtName: "Buxoro",
    eventId: 3,
    eventTitle: "Madaniyat va meros simpoziumlari: Ipak yo'li an'analari",
    presentationTitle: "Buxoro maktabi miniatyurasining tarixiy rivojlanishi",
    abstract: "Buxoro maktabi miniatyura san'ati va uning Markaziy Osiyo san'atiga ta'siri tahlili.",
    documentUrl: "/files/abstract_005.pdf",
    status: "rejected",
    adminComment: "Afsuski, mavzu ushbu tadbirning yo'nalishiga mos kelmaydi.",
    submittedAt: "2026-07-10T11:00:00",
    updatedAt: "2026-07-14T09:00:00",
    translations: {
      uz: { adminComment: "Afsuski, mavzu ushbu tadbirning yo'nalishiga mos kelmaydi." },
      ru: { adminComment: "К сожалению, тема не соответствует направлению данного мероприятия." },
      en: { adminComment: "Unfortunately, the topic does not match the scope of this event." },
    },
  },
];

export const MOCK_FAQS: FAQ[] = [
  {
    id: 1,
    question: "Ariza topshirish uchun qanday hujjatlar talab qilinadi?",
    answer: "Ariza topshirish uchun quyidagi hujjatlar talab qilinadi: tezis matni (PDF yoki DOCX formatida, 300-500 so'z), shaxsiy rasm (JPG yoki PNG, 3x4 format), va ixtiyoriy ravishda pasport nusxasi. Barcha hujjatlar hajmi 10 MB dan oshmasligi kerak.",
    order: 1,
    translations: {
      uz: {
        question: "Ariza topshirish uchun qanday hujjatlar talab qilinadi?",
        answer: "Ariza topshirish uchun quyidagi hujjatlar talab qilinadi: tezis matni (PDF yoki DOCX formatida, 300-500 so'z), shaxsiy rasm (JPG yoki PNG, 3x4 format), va ixtiyoriy ravishda pasport nusxasi. Barcha hujjatlar hajmi 10 MB dan oshmasligi kerak.",
      },
      ru: {
        question: "Какие документы необходимы для подачи заявки?",
        answer: "Для подачи заявки требуются следующие документы: текст тезисов (в формате PDF или DOCX, 300-500 слов), личное фото (JPG или PNG, формат 3x4) и копию паспорта (необязательно). Размер всех файлов не должен превышать 10 МБ.",
      },
      en: {
        question: "What documents are required to apply?",
        answer: "The following documents are required to submit an application: abstract text (PDF or DOCX format, 300-500 words), personal photo (JPG or PNG, 3x4 format), and optionally a passport copy. All documents must not exceed 10 MB in size.",
      },
    },
  },
  {
    id: 2,
    question: "Ariza statusini qanday tekshirish mumkin?",
    answer: "Ariza topshirgandan so'ng sizga noyob Ariza ID beriladi (masalan: CF-2026-000001). Ushbu ID yordamida saytimizning 'Ariza holati' bo'limida yoki asosiy sahifadagi qidiruv maydonida holatni tekshirishingiz mumkin.",
    order: 2,
    translations: {
      uz: {
        question: "Ariza statusini qanday tekshirish mumkin?",
        answer: "Ariza topshirgandan so'ng sizga noyob Ariza ID beriladi (masalan: CF-2026-000001). Ushbu ID yordamida saytimizning 'Ariza holati' bo'limida yoki asosiy sahifadagi qidiruv maydonida holatni tekshirishingiz mumkin.",
      },
      ru: {
        question: "Как проверить статус заявки?",
        answer: "После отправки заявки вам выдается уникальный ID заявки (например: CF-2026-000001). С помощью этого ID вы можете проверить статус в разделе 'Отследить заявку' или в поле поиска на главной странице.",
      },
      en: {
        question: "How can I check my application status?",
        answer: "After submitting your application, you will receive a unique Application ID (e.g. CF-2026-000001). Using this ID, you can check your status in the 'Track application' section or in the search bar on the home page.",
      },
    },
  },
  {
    id: 3,
    question: "Ariza ko'rib chiqish qancha vaqt oladi?",
    answer: "Arizalar odatda 5-10 ish kuni ichida ko'rib chiqiladi. Ko'rib chiqish jarayonida qo'shimcha ma'lumot so'ralishi mumkin. Holat o'zgarishi haqida siz ko'rsatgan elektron pochta manzilingizga xabar yuboriladi.",
    order: 3,
    translations: {
      uz: {
        question: "Ariza ko'rib chiqish qancha vaqt oladi?",
        answer: "Arizalar odatda 5-10 ish kuni ichida ko'rib chiqiladi. Ko'rib chiqish jarayonida qo'shimcha ma'lumot so'ralishi mumkin. Holat o'zgarishi haqida siz ko'rsatgan elektron pochta manzilingizga xabar yuboriladi.",
      },
      ru: {
        question: "Сколько времени занимает рассмотрение заявки?",
        answer: "Заявки обычно рассматриваются в течение 5-10 рабочих дней. В процессе рассмотрения может потребоваться дополнительная информация. Уведомление об изменении статуса будет отправлено на ваш электронный адрес.",
      },
      en: {
        question: "How long does application review take?",
        answer: "Applications are usually reviewed within 5-10 business days. Additional information may be requested during the review process. Notifications about status changes will be sent to your specified email address.",
      },
    },
  },
  {
    id: 4,
    question: "Taqdimot tili qanday bo'lishi kerak?",
    answer: "Taqdimotlar o'zbek, rus yoki ingliz tillarida bo'lishi mumkin. Biroq, tezis matni o'zbek tilida yozilishi tavsiya etiladi. Xalqaro ishtirokchilar uchun ingliz tilidagi tarjima ham qo'shilishi mumkin.",
    order: 4,
    translations: {
      uz: {
        question: "Taqdimot tili qanday bo'lishi kerak?",
        answer: "Taqdimotlar o'zbek, rus yoki ingliz tillarida bo'lishi mumkin. Biroq, tezis matni o'zbek tilida yozilishi tavsiya etiladi. Xalqaro ishtirokchilar uchun ingliz tilidagi tarjima ham qo'shilishi mumkin.",
      },
      ru: {
        question: "На каком языке должна быть презентация?",
        answer: "Презентации могут быть на узбекском, русском или английском языках. Однако текст тезисов рекомендуется составлять на узбекском языке. Для международных участников может быть добавлен перевод на английский язык.",
      },
      en: {
        question: "What language should the presentation be in?",
        answer: "Presentations can be in Uzbek, Russian, or English. However, abstract text is recommended to be in Uzbek. For international participants, an English translation can also be included.",
      },
    },
  },
  {
    id: 5,
    question: "Tadbirda ishtirok etish pullikmi?",
    answer: "Ko'pgina tadbirlarimiz bepul bo'lib, ular tegishli muassasalar tomonidan moliyalashtiriladi. Ayrim maxsus tadbirlar uchun ro'yxatdan o'tish to'lovi belgilanishi mumkin. Batafsil ma'lumot har bir tadbir sahifasida ko'rsatiladi.",
    order: 5,
    translations: {
      uz: {
        question: "Tadbirda ishtirok etish pullikmi?",
        answer: "Ko'pgina tadbirlarimiz bepul bo'lib, ular tegishli muassasalar tomonidan moliyalashtiriladi. Ayrim maxsus tadbirlar uchun ro'yxatdan o'tish to'lovi belgilanishi mumkin. Batafsil ma'lumot har bir tadbir sahifasida ko'rsatiladi.",
      },
      ru: {
        question: "Участие в мероприятии платное?",
        answer: "Большинство наших мероприятий бесплатны и финансируются соответствующими учреждениями. Для некоторых специальных мероприятий может быть установлен регистрационный взнос. Подробная информация указывается на странице каждого мероприятия.",
      },
      en: {
        question: "Is participation in the event paid?",
        answer: "Most of our events are free and funded by relevant institutions. A registration fee may be required for certain special events. Detailed information is provided on each event page.",
      },
    },
  },
  {
    id: 6,
    question: "Bir nechta tadbirga ariza topshirish mumkinmi?",
    answer: "Ha, siz bir nechta tadbirga ariza topshirishingiz mumkin. Har bir tadbir uchun alohida ariza to'ldirilishi kerak. Arizalar mustaqil ko'rib chiqiladi.",
    order: 6,
    translations: {
      uz: {
        question: "Bir nechta tadbirga ariza topshirish mumkinmi?",
        answer: "Ha, siz bir nechta tadbirga ariza topshirishingiz mumkin. Har bir tadbir uchun alohida ariza to'ldirilishi kerak. Arizalar mustaqil ko'rib chiqiladi.",
      },
      ru: {
        question: "Можно ли подать заявку на несколько мероприятий?",
        answer: "Да, вы можете подать заявку на несколько мероприятий. Для каждого мероприятия необходимо заполнить отдельную заявку. Заявки рассматриваются независимо.",
      },
      en: {
        question: "Can I apply for multiple events?",
        answer: "Yes, you can apply for multiple events. A separate application form must be completed for each event. Applications are reviewed independently.",
      },
    },
  },
  {
    id: 7,
    question: "Ariza qabul qilingandan so'ng nima bo'ladi?",
    answer: "Ariza tasdiqlangandan so'ng siz elektron pochta orqali xabar olasiz. Shuningdek, saytda noyob QR kodli taklif xati shakllantiriladi, uni yuklab olishingiz va chop etishingiz mumkin. Tadbir yakunida ishtirokchilarga raqamli sertifikat beriladi.",
    order: 7,
    translations: {
      uz: {
        question: "Ariza qabul qilingandan so'ng nima bo'ladi?",
        answer: "Ariza tasdiqlangandan so'ng siz elektron pochta orqali xabar olasiz. Shuningdek, saytda noyob QR kodli taklif xati shakllantiriladi, uni yuklab olishingiz va chop etishingiz mumkin. Tadbir yakunida ishtirokchilarga raqamli sertifikat beriladi.",
      },
      ru: {
        question: "Что происходит после одобрения заявки?",
        answer: "После одобрения заявки вы получите уведомление по электронной почте. Также на сайте будет сформировано письмо-приглашение с уникальным QR-кодом, которое можно скачать и распечатать. По окончании мероприятия участникам выдается цифровой сертификат.",
      },
      en: {
        question: "What happens after the application is approved?",
        answer: "Once your application is approved, you will receive an email notification. An invitation letter with a unique QR code will also be generated on the website for download and printing. At the end of the event, participants will receive a digital certificate.",
      },
    },
  },
  {
    id: 8,
    question: "Ariza bekor qilish yoki o'zgartirish mumkinmi?",
    answer: "Ariza topshirilgandan so'ng uni tizim orqali o'zgartirish imkoni yo'q. O'zgartirish kerak bo'lsa, uzbamarkaz@umail.uz elektron pochta manziliga yoki +998 71 234-56-78 telefon raqamiga murojaat qiling.",
    order: 8,
    translations: {
      uz: {
        question: "Ariza bekor qilish yoki o'zgartirish mumkinmi?",
        answer: "Ariza topshirilgandan so'ng uni tizim orqali o'zgartirish imkoni yo'q. O'zgartirish kerak bo'lsa, uzbamarkaz@umail.uz elektron pochta manziliga yoki +998 71 234-56-78 telefon raqamiga murojaat qiling.",
      },
      ru: {
        question: "Можно ли отменить или изменить заявку?",
        answer: "После отправки заявку нельзя изменить через систему. Если вам нужно внести изменения, свяжитесь с нами по электронной почте uzbamarkaz@umail.uz или по телефону +998 71 234-56-78.",
      },
      en: {
        question: "Can an application be cancelled or edited?",
        answer: "Once submitted, an application cannot be edited online. If changes are necessary, please contact uzbamarkaz@umail.uz or call +998 71 234-56-78.",
      },
    },
  },
];

export const MOCK_STATS: DashboardStats = {
  totalEvents: 5,
  activeEvents: 3,
  totalApplications: 312,
  todayApplications: 7,
  approved: 98,
  rejected: 23,
  pending: 141,
  underReview: 36,
  infoRequired: 14,
};

export const MOCK_ADMIN_USERS: AdminUser[] = [
  { id: 1, username: "superadmin", fullName: "Aliyev Behruz Mansur o'g'li", email: "b.aliyev@akademiya.uz", role: "super_admin", isActive: true, createdAt: "2025-01-01", lastLogin: "2026-08-04T08:30:00" },
  { id: 2, username: "admin1", fullName: "Rahimova Zulfiya Hamidovna", email: "z.rahimova@akademiya.uz", role: "administrator", isActive: true, createdAt: "2025-03-15", lastLogin: "2026-08-03T17:00:00" },
  { id: 3, username: "moderator1", fullName: "Xasanov Jahongir Akbar o'g'li", email: "j.xasanov@akademiya.uz", role: "moderator", isActive: true, createdAt: "2025-06-01", lastLogin: "2026-08-04T07:45:00" },
];
