# Generated by Django 5.0.4 on 2026-08-07 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation_number', models.CharField(max_length=100, unique=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invitations/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='invitations/qrcodes/')),
                ('is_print_ready', models.BooleanField(default=False)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='applications.application')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'db_table': 'invitations',
            },
        ),
    ]
