---
deployment:
  tasks:
    - export DEPLOYPATH=/home/uzbamala/form.uzbamalaka.uz
    - /bin/cp -R dist/* $DEPLOYPATH/
    - export BACKENDPATH=/home/uzbamala/form.uzbamalaka.uz/backend
    - /bin/cp -R backend/* $BACKENDPATH/
    - mkdir -p $BACKENDPATH/tmp
    - touch $BACKENDPATH/tmp/restart.txt
