---
deployment:
  tasks:
    # Bu yerdagi /home/USERNAME/public_html qismini o'zingizning haqiqiy cPanel login va papkangizga almashtiring!
    # Masalan: /home/ahost123/public_html yoki /home/ahost123/saytim.uz
    - export DEPLOYPATH=/home/USERNAME/public_html
    
    # Biz faqat 'dist' (tayyor build qilingan frontend) papkasini serverga nusxalaymiz
    - /bin/cp -R dist/* $DEPLOYPATH
