import requests

base_url = 'https://form.uzbamalaka.uz/api/v1'
resp = requests.post(f"{base_url}/auth/login/", data={"username": "admin", "password": "Markaz2026!"})
token = resp.json().get('access')
headers = {"Authorization": f"Bearer {token}"}

faqs = [
    {
        "question": "Konferensiyada qatnashish pullikmi?",
        "answer": "Yo'q, O'zbekiston Badiiy akademiyasi tomonidan tashkil etiladigan konferensiyada ishtirok etish mutlaqo bepul.",
        "order": 1,
        "is_active": True,
        "translations": {
            "ru": {
                "question": "Участие в конференции платное?",
                "answer": "Нет, участие в конференции, организуемой Академией художеств Узбекистана, абсолютно бесплатно."
            },
            "en": {
                "question": "Is participation in the conference paid?",
                "answer": "No, participation in the conference organized by the Academy of Arts of Uzbekistan is absolutely free."
            }
        }
    },
    {
        "question": "Tadbirga onlayn qatnashish mumkinmi?",
        "answer": "Ha, ba'zi tadbirlar gibrid formatda o'tkaziladi. Ro'yxatdan o'tish jarayonida 'Online' qatnashish turini tanlashingiz mumkin.",
        "order": 2,
        "is_active": True,
        "translations": {
            "ru": {
                "question": "Можно ли участвовать в мероприятии онлайн?",
                "answer": "Да, некоторые мероприятия проводятся в гибридном формате. При регистрации вы можете выбрать тип участия 'Онлайн'."
            },
            "en": {
                "question": "Is it possible to participate in the event online?",
                "answer": "Yes, some events are held in a hybrid format. During registration, you can select the 'Online' participation type."
            }
        }
    },
    {
        "question": "Sertifikatni qanday olaman?",
        "answer": "Tadbir yakunlanganidan so'ng, tizim orqali elektron sertifikat avtomatik tarzda generatsiya qilinadi. Siz uni 'Holatni kuzatish' sahifasidan yuklab olishingiz mumkin.",
        "order": 3,
        "is_active": True,
        "translations": {
            "ru": {
                "question": "Как я получу сертификат?",
                "answer": "После завершения мероприятия в системе автоматически сгенерируется электронный сертификат. Вы сможете скачать его на странице 'Отследить статус'."
            },
            "en": {
                "question": "How do I get a certificate?",
                "answer": "After the event is completed, an electronic certificate will be automatically generated by the system. You can download it from the 'Track status' page."
            }
        }
    },
    {
        "question": "Mening arizam holatini qayerdan ko'rsam bo'ladi?",
        "answer": "Saytning yuqori qismidagi 'Holatni kuzatish' tugmasi orqali arizangiz ID raqamini kiritib, barcha ma'lumotlarni ko'rishingiz mumkin.",
        "order": 4,
        "is_active": True,
        "translations": {
            "ru": {
                "question": "Где я могу посмотреть статус моей заявки?",
                "answer": "Вы можете просмотреть всю информацию, введя ID вашей заявки через кнопку 'Отследить статус' в верхней части сайта."
            },
            "en": {
                "question": "Where can I see the status of my application?",
                "answer": "You can view all the information by entering your application ID through the 'Track status' button at the top of the site."
            }
        }
    }
]

for faq in faqs:
    r = requests.post(f"{base_url}/faqs/admin/", json=faq, headers=headers)
    print(r.status_code, r.text)

print("FAQs created!")
