# Generated by Django 5.0.4 on 2026-08-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization_name', models.CharField(default='CENTR FORM', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/logo/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='settings/favicon/')),
                ('footer_text', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('social_links', models.TextField(blank=True)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('sms_api_provider', models.CharField(blank=True, max_length=50)),
                ('sms_api_key', models.CharField(blank=True, max_length=255)),
                ('certificate_template', models.TextField(blank=True)),
                ('invitation_template', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Organization setting',
                'verbose_name_plural': 'Organization settings',
                'db_table': 'organization_settings',
            },
        ),
    ]
