# Generated by Django 5.0.4 on 2026-08-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='map_url',
            field=models.TextField(blank=True, verbose_name='Google Maps URL'),
        ),
    ]
