# Generated by Django 5.0.4 on 2026-08-07 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('conference', 'Konferensiya'), ('forum', 'Forum'), ('exhibition', "Ko'rgazma"), ('symposium', 'Simpozium'), ('workshop', 'Seminar-trening'), ('seminar', 'Seminar')], max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Rejalashtirilgan'), ('ongoing', 'Jarayonda'), ('completed', 'Yakunlangan')], default='planned', max_length=20)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_deadline', models.DateField()),
                ('venue', models.CharField(max_length=500)),
                ('banner', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('program_pdf', models.FileField(blank=True, null=True, upload_to='events/programs/')),
                ('participant_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('registration_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Tadbirlar',
                'db_table': 'events',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='events.event')),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Galereya rasmlari',
                'db_table': 'event_gallery',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
