# Generated by Django 5.0.4 on 2026-08-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('conference', 'Konferensiya'), ('forum', 'Forum'), ('exhibition', "Ko'rgazma"), ('symposium', 'Simpozium'), ('workshop', 'Seminar-trening'), ('seminar', 'Seminar'), ('article_call', 'Ilmiy jurnal (maqola/tezis qabuli)')], max_length=20),
        ),
    ]
