# Generated by Django 5.0.4 on 2026-08-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='translations',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
