# Generated by Django 5.0.4 on 2026-08-07 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Certificate template',
                'verbose_name_plural': 'Certificate templates',
                'db_table': 'certificate_templates',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_number', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('issued', 'Berildi'), ('revoked', 'Bekor qilindi')], default='pending', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificates/qrcodes/')),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='applications.application')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='certificates.certificatetemplate')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'db_table': 'certificates',
            },
        ),
    ]
