# Generated by Django 5.0.4 on 2026-09-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
