# Generated by Django 5.0.4 on 2026-08-07 06:51

import apps.applications.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(default=apps.applications.models.generate_application_id, editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=300)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(max_length=500)),
                ('position', models.CharField(max_length=300)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('presentation_title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='applications/documents/')),
                ('passport', models.FileField(blank=True, null=True, upload_to='applications/passports/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='applications/photos/')),
                ('invitation_pdf', models.FileField(blank=True, null=True, upload_to='applications/invitations/')),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='applications/certificates/')),
                ('status', models.CharField(choices=[('submitted', 'Yuborildi'), ('under_review', "Ko'rib chiqilmoqda"), ('info_required', "Qo'shimcha ma'lumot kerak"), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='submitted', max_length=20)),
                ('admin_comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='events.event')),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'db_table': 'applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
