# Generated by Django 5.0.4 on 2026-08-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(default="O'zbekiston", max_length=255, verbose_name='Mamlakat'),
        ),
    ]
