# Generated by Django 5.0.4 on 2026-09-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attendance_type',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='presentation_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
