# Generated by Django 5.0.4 on 2026-09-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user_reply',
            field=models.TextField(blank=True, verbose_name='Foydalanuvchi javobi'),
        ),
    ]
