# Generated by Django 5.0.4 on 2026-10-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_user_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='certificate_pdf',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='applications/certificates/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='document',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='applications/documents/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='invitation_pdf',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='applications/invitations/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='passport',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='applications/passports/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='applications/photos/'),
        ),
    ]
