# Generated by Django 5.2.11 on 2026-10-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_applicationauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='edit_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Tahrirlangan'),
        ),
        migrations.AddField(
            model_name='application',
            name='original_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Birinchi yuborilgan versiya'),
        ),
    ]
