# Generated by Django 5.2.11 on 2026-10-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_application_edit_count_application_edited_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Yuborildi'), ('under_review', "Ko'rib chiqilmoqda"), ('info_required', "Qo'shimcha ma'lumot kerak"), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi'), ('edited', 'Tahrirlandi')], default='submitted', max_length=20),
        ),
    ]
