# Generated by Django 5.0.4 on 2026-08-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qr_type', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('token', models.CharField(max_length=255, unique=True)),
                ('hash_value', models.CharField(max_length=64)),
                ('image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'QR kod',
                'verbose_name_plural': 'QR kodlar',
                'db_table': 'qr_codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
